version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ${MULTIVERSE_SECRETS_PATH}:/usr/local/.secrets/apple/
    env_file:
      - .env
    networks:
      - web_network

  background:
    build:
      context: .
      dockerfile: Dockerfile.background
    volumes:
      - .:/app
      - ${MULTIVERSE_SECRETS_PATH}:/usr/local/.secrets/apple/
    env_file:
      - .env
    depends_on:
      - web
    networks:
      - web_network
    deploy:
      replicas: 4

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${MULTIVERSE_SECRETS_PATH}/ssl/:/etc/nginx/ssl/   # SSL certificates
    ports:
      - "443:443"
    depends_on:
      - web
    networks:
      - web_network

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - web_network

networks:
  web_network:
    driver: bridge

volumes:
  postgres_data: