version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env

  background:
    build:
      context: .
      dockerfile: Dockerfile.background
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - web

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/letsencrypt/   # SSL certificates
    ports:
      - "443:443"