version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ${MULTIVERSE_SECRETS_PATH}:/usr/local/.secrets/apple/
      - logs_data:/var/log/app
    env_file:
      - .env
    restart: always
    networks:
      - web_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "100"

  background:
    build:
      context: .
      dockerfile: Dockerfile.background
    volumes:
      - .:/app
      - ${MULTIVERSE_SECRETS_PATH}:/usr/local/.secrets/apple/
      - logs_data:/var/log/app
    env_file:
      - .env
    depends_on:
      - web
    restart: always
    networks:
      - web_network
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: '0.50'    # max 0.5 CPU core
          memory: 512M    # hard memory limit
        reservations:
          cpus: '0.25'    # scheduler tries to keep this much free
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "100"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${MULTIVERSE_SECRETS_PATH}/ssl/:/etc/nginx/ssl/   # SSL certificates
      - logs_data:/var/log/nginx
    ports:
      - "443:443"
    depends_on:
      - web
    restart: always
    networks:
      - web_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "100"

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
      - logs_data:/var/log/postgresql
    networks:
      - web_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "100"

networks:
  web_network:
    driver: bridge

volumes:
  postgres_data:
  logs_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/logs