version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env

  background:
    build:
      context: .
      dockerfile: Dockerfile.background
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - web
